name: Android Fastlane

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  internal:
    name: Build & Upload Internal
    runs-on: ubuntu-latest

    # Đưa secrets vào ENV ở cấp job để có thể dùng trong điều kiện if
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
      FASTLANE_SKIP_UPDATE_CHECK: "1"
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Create Google Play credentials
        # Nếu cần, có thể thêm điều kiện if để chỉ chạy khi secret có giá trị
        if: ${{ env.PLAY_SERVICE_ACCOUNT_JSON != '' }}
        run: |
          mkdir -p android/fastlane
          echo "$PLAY_SERVICE_ACCOUNT_JSON" > android/fastlane/service-account.json

      # Bước này CHỈ chạy nếu keystore đã được set trong secrets
      - name: Prepare keystore (optional)
        if: ${{ env.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks

          # LƯU Ý: dùng EOF (không có quote) để biến được expand ra giá trị thực
          cat > android/key.properties <<EOF
          storePassword=${ANDROID_KEYSTORE_PASSWORD}
          keyPassword=${ANDROID_KEY_PASSWORD}
          keyAlias=${ANDROID_KEY_ALIAS}
          storeFile=upload-keystore.jks
          EOF

      - name: Build & Upload to Internal
        working-directory: android
        run: |
          bundle exec fastlane android internal
